### ISSUE TITLE
Improve json in heredoc by using data source and jsonencode

### ISSUE THREAD

**Issue by antonbabenko** [terraform-aws-modules/terraform-aws-atlantis#13]
Instead of this - https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/8d873d4a63d80fda277561a36697086741c8beaa/main.tf#L226-L282

Do something like this:
```hcl
locals {
  log_group = "test-group"
  definition = {
    name = "example"
    memory = "500"
  }
  default_definition = {
    name = "test"
    image = "test_image"
    memory = 200
    essential = true
    command = "node"
    portMappings = [
        {
          containerPort = 8008
          hostPort = 80
        }
      ]
    logConfiguration = {
        logDriver = "awslogs"
        options = {
          awslogs-group = "${local.log_group}"
          awslogs-region = "us-west-2"
      }
    }

  }
}

output "test" {
  value = "${jsonencode(merge(local.default_definition, local.definition))}"
}
``` 

Kudos to @osterman

**Comment by ldormoy** [comment]
I tried to implement this, but unfortunately I'm stopped by a limitation of Terraform.

The limitation is a combination of these 2 issues:
https://github.com/hashicorp/terraform/issues/4797
https://github.com/hashicorp/terraform/issues/17033

So first, container_definitions does not accept quoted numeric values, as explained in the first issue. So we have to make sure that numeric values are defined without quotes, otherwise the following error occurs:

`module.atlantis.aws_ecs_task_definition.atlantis: ECS Task Definition container_definitions is invalid: Error decoding JSON: json: cannot unmarshal string into Go struct field ContainerDefinition.Cpu of type int64`

The second issue is clearly a bug from the jsonencode() function: jsonencode() replaces numeric values by strings. There is a workaround in the comments, using a replace() regex to identify quoted strings and remove the quotes.
But then it also removes the quotes from the ATLANTIS_PORT environment value, which SHOULD have quotes, otherwise you get the following error:

`module.atlantis.aws_ecs_task_definition.atlantis: ECS Task Definition container_definitions is invalid: Error decoding JSON: json: cannot unmarshal number into Go value of type string`

So I thought of defining separately the environment map and merge it later, but this would mean:
* convert the default definition to json
* then remove the quotes for integer values
* then somehow convert the default def back to a terraform map
* then merge the default def map with the env map
* finally encode the result to json

You can see that it becomes a very complicated solution, just to avoid using an template file. So I would kindly suggest to use the solution proposed in #9 

What do you think?

**Comment by antonbabenko** [comment]
Well, if it does not work with `jsonencode` then the solution from #9 is the only option.

I wonder if @maartenvanderhoef and @osterman have experienced similar issues with `jsonencode`?

**Comment by ldormoy** [comment]
[Cloudposse PR 9](https://github.com/cloudposse/terraform-aws-ecs-container-definition/pull/9) provides some regex magic that solves this issue :+1:

**Comment by ldormoy** [comment]
Okay from a technical PoV it will work.
Can you explain more clearly the difference between `definition` and `default_definition` in your example?

My current implementation only has one definition variable:
```hcl
locals {
# Container definition
  definition = {
    name      = "${var.name}"
    cpu       = "256"
    memory    = 512
    essential = "true"
    image     = "${local.atlantis_image}"

    logConfiguration = {
      logDriver = "awslogs"

      options = {
        awslogs-group         = "${var.name}"
        awslogs-region        = "${data.aws_region.current.name}"
        awslogs-stream-prefix = "master"
      }
    }

    mountPoints = []
    name        = "${var.name}"

    portMappings = [
      {
        containerPort = 4141
        hostPort      = 4141
        protocol      = "tcp"
      },
    ]

    volumesFrom = []

    environment = [
      {
        name  = "ATLANTIS_ALLOW_REPO_CONFIG"
        value = "${var.allow_repo_config}"
      },
      {
        name  = "ATLANTIS_LOG_LEVEL"
        value = "debug"
      },
      {
        name  = "ATLANTIS_PORT"
        value = "4141"
      },
      {
        name  = "ATLANTIS_ATLANTIS_URL"
        value = "https://${coalesce(element(concat(aws_route53_record.atlantis.*.fqdn, list("")), 0), module.alb.dns_name)}"
      },
      {
        name  = "ATLANTIS_GH_USER"
        value = "${var.atlantis_github_user}"
      },
      {
        name  = "ATLANTIS_GH_TOKEN"
        value = "${var.atlantis_github_user_token}"
      },
      {
        name  = "ATLANTIS_GH_WEBHOOK_SECRET"
        value = "${random_id.webhook.hex}"
      },
      {
        name  = "ATLANTIS_REPO_WHITELIST"
        value = "${join(",", var.atlantis_repo_whitelist)}"
      },
    ]
  }
}
```

**Comment by antonbabenko** [comment]
I forgot why do we need to do this? :trollface: 

Can someone remind me, please?

**Comment by antonbabenko** [comment]
Right, I think it does not worth it unless there is an elegant solution which is easy to work with (jsonencode hacks are not nice). Also, I don't think we need such a flexibility to manipulate container definitions.

Closing this for now.

**Comment by antonbabenko** [comment]
Thanks for the link.

I probably will, but don't want to rewrite it just now because _it works_. Maybe later when I work on this module again.
