### ISSUE TITLE
Option to add sidecars 

### ISSUE THREAD

**Issue by nitrocode** [terraform-aws-modules/terraform-aws-atlantis#133]
Instead of overwriting the entire container definition, it would be nice to be able to append sidecars. For instance, I'd like to use the ddagent sidecar for datadog metrics and fluentbit sidecar to push logs to datadog.

**Comment by marcoceppi** [comment]
@antonbabenko this can be closed now, thank you again!

**Comment by antonbabenko** [comment]
Great @marcoceppi !

@nitrocode Please use [v2.26.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/releases/v2.26.0) for this feature.

**Comment by jaredtkatz** [comment]
Raising a question here since this is the most relevant issue I can find...  Does anyone (@antonbabenko?) have thoughts on somehow exposing the `volume` block for the Atlantis `ecs_task_definition` as a top-level variable for this module so users can optionally specify a Docker or EFS volume? I've personally been bumping up against the limits of the 20GB of storage provided by default for Fargate tasks. The ability to specify a Docker or EFS volume for the Atlantis task's container(s) would be nice. However, this might already be possible and I'm missing something, so I thought I'd sanity check here before creating an issue. Thanks!
