### ISSUE TITLE
Leverage EFS to persist atlantis locks between deployments?

### ISSUE THREAD

**Issue by mwarkentin** [terraform-aws-modules/terraform-aws-atlantis#206]
## Is your request related to a problem? Please describe.

Every time we make a change that requires redeploying our atlantis container, we lose all of the locks on PRs that atlantis currently has. These locks are persisted to the file system which is not maintained between containers.

## Describe the solution you'd like.
I'm wondering if the module could configure an EFS mount where the file system locks can be maintained, so that they persist between deployments.

## Describe alternatives you've considered.
Currently we have to capture the current list of locks, deploy atlantis, and then go to each of the PRs to reacquire the locks.

**Comment by mwarkentin** [comment]
Stayin' alive..

**Comment by MarkIannucci** [comment]
I have some work underway to fix this issue in the [PersistInEFS branch in my fork](https://github.com/MarkIannucci/terraform-aws-atlantis/tree/PersistInEFS).

With the Ephemeral storage functionality introduced in #229, I'm a bit torn on how to proceed.  My feeling is that we'd want to use EFS by default if the configuration doesn't indicate the user's intent to use larger Ephemeral storage, and that is the direction that I plan to use, unless I hear otherwise.

I also had to adjust the max and minimum deployment percent variables to 100 and 0 respectively because Atlantis gets angry if the BoltDb is in use when it gets turned on.  This means that redeployments now cause short outages (in my experience less than 5 minutes).  I think that's a better situation than issue identified here where data gets lost if the container terminates for any reason.  Ultimately, the short outage issue will get fixed by #19.

**Comment by MarkIannucci** [comment]
@mwarkentin , I submitted #247 a few days ago.  I've been running it for my personal repos over the last two weeks, and I've been happy with it. I don't know if you want to give it a shot in your environment.  If you do and want to share your results I think it will provide another helpful datapoint for the PR which will increase everyone's confidence :-)

**Comment by mwarkentin** [comment]
@MarkIannucci thanks! I'll check with the team, I'm not responsible for Atlantis at our company anymore. Looks like there are some code review requests from Anton though. :)
