### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by teeejas** [terraform-aws-modules/terraform-aws-atlantis#227]
I am stuck on this error what is it looking for?

   on main.tf line 13, in module "atlantis":
│   13: module "atlantis" {
│ The argument "atlantis_repo_allowlist" is required, but no definition was found.

Here is what I have in my tfvars
atlantis_allowed_repo_names = ["jks-lab","jks-lab2"]

atlantis_repo_allowlist =["github.com/teeejas/*","github.com/teeejas/jks-lab"]

Tried all possible combinations.. nothing works

**Comment by antonbabenko** [comment]
Double-check that you don't have `atlantis_repo_whitelist` anywhere in your code since it was renamed (see #198) and sometimes the code may referring to it.

Also, make sure that you are using the latest version of the module.

PS: Please open the issue following the template and provide the configuration you are using.

**Comment by teeejas** [comment]
# Atlantis
atlantis_allowed_repo_names = ["awesome-repo", "another-awesome-repo"]
atlantis_repo_allowlist = ["github.com/terraform-aws-modules/*"]

What is the expected value for this ?
I am assuming this is my github link and my repos right?

**Comment by antonbabenko** [comment]
This looks correct to me.
