### ISSUE TITLE
When using SSM parameter store for Github token, it stores the token in plain text.

### ISSUE THREAD

**Issue by JMGoldsmith** [terraform-aws-modules/terraform-aws-atlantis#39]
When using an access token and storing in to SSM it stores the token as plain text. Am I missing something in the vars?

I tested the access to the parameters via a new user with generic power user rights. That user could see the secret in plain text.

When encrypting the token via a custom key it fails to decrypt.(the ARN has been placed in to the vars file, the role execution task has the decrypt action set.)

Thoughts?

**Comment by antonbabenko** [comment]
Yes, token (as well as all other values) is stored in Terraform state in plain text. This is how Terraform works.

Atlantis needs all environment variables to be decrypted in order to work.

The simplest thing you can do is to secure access to your state file, but anyone who will be able to run `terraform apply` will have to have access to it thus will be able to see unencrypted values.

Did I answer your question?

**Comment by JMGoldsmith** [comment]
Apologies if I wasn't clear, but it was more in the SSM side of things where the secret was stored in plain text, but only for powerusers and admins. We have slightly looser permissions for a small subset of users and have now locked those down. Closing, but thank you for your reply!!
