### ISSUE TITLE
Provide option to make ALB internal

### ISSUE THREAD

**Issue by chadasapp** [terraform-aws-modules/terraform-aws-atlantis#69]
What it says in the description. In our setup it would be ideal if the load balancer was internal, on the private subnets so it's not publicly routed. It seems like it'd be fairly straightforward to implement.

**Comment by mlcooper** [comment]
I agree.  I've been working with this module for the first time this week and just about have it up and running in my existing AWS VPC.  What I did do is try to 'fool' it and gave it my private subnets for the ALB since I don't want this exposed externally.  So the value I gave it for `private_subnet_ids` is the same as `public_subnet_ids`.  I _think_ it should work, but I'm not quite ready to test yet.

**Comment by mlcooper** [comment]
This worked...I had to fork this terraform-aws-atlantis repo and add
```
load_balancer_is_internal = true
```
to the `module "alb" {}` block.

**Comment by geota** [comment]
any progress/appetite to merge a feature like this? i would like to lock down ALB to make it fully internal, happy to submit a PR

**Comment by martinmosegaard** [comment]
Hi @geota . I am trying to get this working in a PR. Let me know what you think.

**Comment by antonbabenko** [comment]
This has been fixed in #99. Please use [v2.9.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/releases/v2.9.0) which has been just released.

For some users, this release may require some ALB resource recreation described in [ALB upgrade guide 5.0](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/UPGRADE-5.0.md).

**Comment by kneufeld-pbp** [comment]
Was it by design to always use public subnets when internal is set to `true`?  Our assumption was the module would use the `private_subnet_ids` when we provided the `vpc_id`; this assumption will error and our work-around is to add the set the public_subnet_ids with our `private_subnet_ids`

**Comment by antonbabenko** [comment]
@kneufeld-pbp This is just a bad name for the variable. Previously, there was no way to make ALB internal, so the public subnets were always used.
